### ISSUE TITLE
Error "Class name is not registered for the component session"

### ISSUE THREAD

**Issue by jfoliveira** [rainlab/vanilla-theme#1]
Just added the theme to a fresh installation, checked for updates to download it, and then activated it.

When I load the front end I see the following error message:

`Class name is not registered for the component session. Check the component plugin.
/var/www/my_project/modules/cms/classes/ComponentManager.php line 200`

Any ideas?

**Comment by daftspunk** [comment]
Yes, make sure these plugins are installed:
    - RainLab.User
    - RainLab.Blog
    - RainLab.Forum

**Comment by jfoliveira** [comment]
It worked after installing the 3 plugins.
Thanks Samuel!

**Comment by ted-at-roar** [comment]
I'm getting this error for both front-end and backend. I guess I would need to manually install the plugins to resolve? Can not access the GUI to do it. Clarification?

**Comment by ted-at-roar** [comment]
Resolved by adding plugins to Project and then running:

`php artisan october:update`

Twice, actually. Guess the first run didn't download the latest version of the plugins.
