### ISSUE TITLE
Can't save and update company name, address

### ISSUE THREAD

**Issue by chrisvidal** [rainlab/vanilla-theme#11]
Can't save nor update company name, address int the account profile page `/account/profile`

> `"An exception has been thrown during the rendering of a template ("Le modèle partiel "@form-select-country" est introuvable.") in "/Users/christophevidal/Sites/oc-christophevidal/themes/vanilla-theme-master/partials/account/field-address.htm" at line 84.`

**Comment by cemkoker** [comment]
Same here.

**Comment by daftspunk** [comment]
This would happen if the RainLab.Location plugin was not installed, it is a dependency of RainLab.UserPlus. Did it not install automatically?

Run the following command to install missing dependencies:

```
php artisan plugin:check
```

**Comment by chrisvidal** [comment]
Thanks @daftspunk 

but i confirm that the `location` plugin is already installed on my setup

```
php artisan plugin:check
Checking Dependencies...
All dependencies installed
```

**Comment by daftspunk** [comment]
Does this file exist **plugins/rainlab/location/components/location/form-select-country.htm**?

**Comment by chrisvidal** [comment]
seems like it yes

<img width="318" alt="image" src="https://github.com/user-attachments/assets/d28a5509-91f7-4b21-a11c-ae2e8912eb16">

**Comment by daftspunk** [comment]
Is the `[location]` component used on the page?

**Comment by chrisvidal** [comment]
no its not on the page `account/profile` neither in the layout

**Comment by daftspunk** [comment]
The repo shows that its there: https://github.com/rainlab/vanilla-theme/blob/master/pages/account/profile.htm#L15

Perhaps you need to update your theme?

**Comment by chrisvidal** [comment]
yes you are gith, it was there below....but even with it the error is still showing up.

**Comment by daftspunk** [comment]
Hmm interesting, I can't seem to reproduce it. What steps are you taking for the error to appear?

**Comment by chrisvidal** [comment]
first i navigate to the homepage `http://vanilla.oc-christophevidal.test/`
then i navigate to thew view profile `http://vanilla.oc-christophevidal.test/account/profile`
then I click on the `edit` button near the Address label which uncollapse a fieldset of fields to key in my address (btw i'm in no address book mode)
then I key in my address 


and click save
and get the error

**Comment by daftspunk** [comment]
Great! I found the issue, thanks @chrisvidal 

>  (btw i'm in no address book mode)

This part was the missing piece of information...

There was an issue in the October CMS core and a patch has been included in OCMS v3.7.5

**Comment by chrisvidal** [comment]
awesonness !

**Comment by dathwa** [comment]
> Great! I found the issue, thanks @chrisvidal
> 
> > (btw i'm in no address book mode)
> 
> This part was the missing piece of information...
> 
> There was an issue in the October CMS core and a patch has been included in OCMS v3.7.5

@daftspunk where exactly can i find the fixes for this? Still waitong for 3.7.5 to be pubished, but i need the fix for a live site. Thanks

**Comment by dathwa** [comment]
@daftspunk - Can we re-open this?
See `https://github.com/rainlab/location-plugin/blob/master/models/State.php` 
I found that only after editing this function was it fixed.
```
public static function getObjectList($countryId)
    {
        if (self::$objectList) {
            return self::$objectList;
        }

        return self::$objectList[$countryId] = self::whereCountryId($countryId)->orderBy('name', 'asc')->get();
    }
```
change to

```
public static function getObjectList($countryId)
    {
        if (isset(self::$objectList[$countryId])) {
            return self::$objectList[$countryId];
        }

        return self::$objectList[$countryId] = self::whereCountryId($countryId)->orderBy('name', 'asc')->get();
    }
```

**Comment by daftspunk** [comment]
I made the change here: 

https://github.com/rainlab/location-plugin/commit/8ffe7c33eba1d4cfaa3ad6596137359f77db3668

**Comment by dathwa** [comment]
> I made the change here:
> 
> [rainlab/location-plugin@8ffe7c3](https://github.com/rainlab/location-plugin/commit/8ffe7c33eba1d4cfaa3ad6596137359f77db3668)

I'm afraid that does not work for me.

`Next Twig\Error\RuntimeError: An exception has been thrown during the rendering of a template ("Method October\Rain\Database\Collection::id does not exist.") in "\plugins/rainlab/location/components/location/form-select-state.htm" at line 12. in \vendor\twig\twig\src\Template.php:401
`
This does...  
```
 public static function getObjectList($countryId)
    {
        if (isset(self::$objectList[$countryId])) {
            return self::$objectList[$countryId];
        }
        return self::$objectList[$countryId] = self::whereCountryId($countryId)->orderBy('name', 'asc')->get();
    }
```
