### ISSUE TITLE
alert-dialog.js

### ISSUE THREAD

**Issue by chrisvidal** [rainlab/vanilla-theme#12]
Hi,
I'am trying to make use of the component `alert-dialog.js` but I can't seem to be able to make it work
I'd like to use it for confirm and message alert since it seems to made for this purpose.

thanks

**Comment by daftspunk** [comment]
Hey Chris,

Here you go:
```js
<script>
// Show an alert
alertMessage('Hello');

// Show a confirm message
confirmMessage('Yo', function(ok) { console.log(ok); });
</script>
```

**Comment by chrisvidal** [comment]
thanks @daftspunk 
oh its a js call ... haha...I was trying to use it with ajax and dispatchLiveEvent (as the password confirmation)
its the promise I dont really get around actually

**Comment by daftspunk** [comment]
Yes... You could make a dispatchBrowserEvent for it... That would be cool.
